import type { Metadata } from 'next'
import '../globals.css'
import { Noto_Sans_KR } from 'next/font/google'
import styles from './layout.module.css'
import cn from 'classnames'
import { Header } from './components/Header/Header'
import { Sidebar } from './components/Sidebar/Sidebar'
import { Footer } from './components/Footer/Footer'

export const metadata: Metadata = {
	title: 'App new',
	description: 'Generated by create next app',
}

const notoSans = Noto_Sans_KR({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['cyrillic', 'latin'],
	display: 'swap',
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>): JSX.Element {
	return (
		<html lang='ru'>
			<body className={cn(notoSans.className, styles.wrap)}>
				<Header className={styles.header} />
				<Sidebar className={styles.sidebar} />
				<div className={styles.body}>{children}</div>
				<Footer className={styles.footer} />
			</body>
		</html>
	)
}
