import type { Metadata } from 'next'
import { ReactNode } from 'react'

export const metadata: Metadata = {
	title: 'Template',
	description: 'Generated by create next app',
}

export default function AboutLayout({
	children,
	one,
	two,
}: Readonly<{
	children: React.ReactNode
	one: ReactNode
	two: ReactNode
}>): JSX.Element {
	return (
		<div style={{ padding: 120 }}>
			{children}
			{one}
			{two}
		</div>
	)
}
